import {
  UserProfile,
  Department,
  Technician,
  WorkOrder,
  SystemSettings,
} from './types';

export const initialSystemSettings: SystemSettings = {
  hotelName: 'Ceyvista Engineering',
  hotelLogo: '/logo.png',
  hotelAddress: 'Colombo, Sri Lanka',
  hotelContactEmail: 'engineering@ceyvista.com',
  hotelContactPhone: '+94 11 765 4321',
  p1Label: 'P1 – EMERGENCY 🔴',
  p2Label: 'P2 – HIGH 🟠',
  p3Label: 'P3 – NORMAL 🟡',
  p4Label: 'P4 – PLANNED 🟢',
  soundAlertEnabled: true,
};

export const initialDepartments: Department[] = [
  { id: 'dept-fo', name: 'Front Office', code: 'FO', active: true },
  { id: 'dept-hk', name: 'Housekeeping', code: 'HK', active: true },
  { id: 'dept-fb', name: 'F&B Service', code: 'FB', active: true },
  { id: 'dept-kit', name: 'Kitchen & Culinary', code: 'KIT', active: true },
  { id: 'dept-sec', name: 'Security & Safety', code: 'SEC', active: true },
  { id: 'dept-mgmt', name: 'General Management', code: 'MGMT', active: true },
  { id: 'dept-admin', name: 'Administration & HR', code: 'ADMIN', active: true },
  { id: 'dept-spa', name: 'Spa & Wellness', code: 'SPA', active: true },
];

export const initialTechnicians: Technician[] = [
  { id: 'tech-kasun', name: 'Kasun Perera', department: 'Engineering', specialization: 'Electrical & Automation', active: true, phone: '+94 77 123 4567' },
  { id: 'tech-nimal', name: 'Nimal Silva', department: 'Engineering', specialization: 'Plumbing & Water Systems', active: true, phone: '+94 77 234 5678' },
  { id: 'tech-pradeep', name: 'Pradeep Fernando', department: 'Engineering', specialization: 'Air Conditioning / HVAC', active: true, phone: '+94 77 345 6789' },
  { id: 'tech-suresh', name: 'Suresh Bandara', department: 'Engineering', specialization: 'Carpentry & General Civil', active: true, phone: '+94 77 456 7890' },
];

export const initialUsers: UserProfile[] = [
  {
    id: 'user-admin',
    name: 'ME Colombo Administrator',
    username: 'mecolomboadmin',
    email: 'mecolomboadmin@mecolombo.com',
    password: 'mecolombo',
    role: 'ADMIN',
    department: 'Administration',
    active: true,
  },
  {
    id: 'user-chief-eng',
    name: 'Eng. Kasun Wijesinghe',
    username: 'chiefeng',
    email: 'chief.eng@mecolombo.com',
    password: 'password123',
    role: 'ENGINEERING',
    department: 'Engineering',
    active: true,
    phone: '+94 77 000 1111',
  },
  {
    id: 'user-supervisor',
    name: 'Sunil Shantha',
    username: 'supervisor',
    email: 'supervisor.eng@mecolombo.com',
    password: 'password123',
    role: 'ENGINEERING',
    department: 'Engineering',
    active: true,
    phone: '+94 77 000 2222',
  },
  {
    id: 'user-tech-kasun',
    name: 'Kasun Perera',
    username: 'kasun',
    email: 'kasun.elec@mecolombo.com',
    password: 'password123',
    role: 'TECHNICIAN',
    department: 'Engineering',
    active: true,
    phone: '+94 77 123 4567',
  },
  {
    id: 'user-tech-nimal',
    name: 'Nimal Silva',
    username: 'nimal',
    email: 'nimal.plumb@mecolombo.com',
    password: 'password123',
    role: 'TECHNICIAN',
    department: 'Engineering',
    active: true,
    phone: '+94 77 234 5678',
  },
  {
    id: 'user-tech-pradeep',
    name: 'Pradeep Fernando',
    username: 'pradeep',
    email: 'pradeep.hvac@mecolombo.com',
    password: 'password123',
    role: 'TECHNICIAN',
    department: 'Engineering',
    active: true,
    phone: '+94 77 345 6789',
  },
  {
    id: 'user-tech-suresh',
    name: 'Suresh Bandara',
    username: 'suresh',
    email: 'suresh.civil@mecolombo.com',
    password: 'password123',
    role: 'TECHNICIAN',
    department: 'Engineering',
    active: true,
    phone: '+94 77 456 7890',
  },
  {
    id: 'user-exec-fo',
    name: 'Anoma Gunasekara',
    username: 'frontoffice',
    email: 'frontoffice@mecolombo.com',
    password: 'password123',
    role: 'EXECUTIVE',
    department: 'Front Office',
    active: true,
  },
  {
    id: 'user-exec-hk',
    name: 'Dilshan Rathnayake',
    username: 'housekeeping',
    email: 'housekeeping@mecolombo.com',
    password: 'password123',
    role: 'EXECUTIVE',
    department: 'Housekeeping',
    active: true,
  },
  {
    id: 'user-exec-fb',
    name: 'Rohan Jayasuriya',
    username: 'fbservice',
    email: 'fb@mecolombo.com',
    password: 'password123',
    role: 'EXECUTIVE',
    department: 'F&B Service',
    active: true,
  },
  {
    id: 'user-exec-gm',
    name: 'Dharshana Ratnayake',
    username: 'gm',
    email: 'gm@mecolombo.com',
    password: 'password123',
    role: 'EXECUTIVE',
    department: 'General Management',
    active: true,
  },
];

const now = new Date();
const minutesAgo = (m: number) => new Date(now.getTime() - m * 60000).toISOString();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();

export const initialWorkOrders: WorkOrder[] = [
  {
    id: 'wo-0045',
    workOrderNumber: 'WO-2026-0045',
    reportedBy: 'Anoma Gunasekara',
    reportedById: 'user-exec-fo',
    departmentName: 'Front Office',
    location: 'Guest Room',
    roomNumber: '305',
    category: 'AC',
    title: 'AC Not Cooling and Water Dripping from Ceiling Vent',
    description: 'Guest checked in at 2 PM. Bedroom air conditioner not cooling down, temperature is 28°C and water is dripping on the desk carpet.',
    guestAffected: true,
    priority: 'P1',
    suggestedPriority: 'P1',
    priorityRationale: 'Guest in-house with non-functioning AC and water leak hazard.',
    status: 'NEW',
    reportedAt: minutesAgo(2),
    createdAt: minutesAgo(2),
    updatedAt: minutesAgo(2),
    history: [
      {
        id: 'hist-45-1',
        workOrderId: 'wo-0045',
        status: 'NEW',
        timestamp: minutesAgo(2),
        actorName: 'Anoma Gunasekara (Front Office)',
        note: 'Reported issue from Executive Portal',
      },
    ],
  },
  {
    id: 'wo-0044',
    workOrderNumber: 'WO-2026-0044',
    reportedBy: 'Dilshan Rathnayake',
    reportedById: 'user-exec-hk',
    departmentName: 'Housekeeping',
    location: 'Guest Room',
    roomNumber: '212',
    category: 'Water',
    title: 'No Hot Water in Bathroom Shower',
    description: 'Hot water line running lukewarm only. Guest requested technician assistance.',
    guestAffected: true,
    priority: 'P2',
    suggestedPriority: 'P2',
    priorityRationale: 'Guest room hot water supply issue.',
    status: 'NEW',
    reportedAt: minutesAgo(8),
    createdAt: minutesAgo(8),
    updatedAt: minutesAgo(8),
    history: [
      {
        id: 'hist-44-1',
        workOrderId: 'wo-0044',
        status: 'NEW',
        timestamp: minutesAgo(8),
        actorName: 'Dilshan Rathnayake (Housekeeping)',
        note: 'Reported issue from Executive Portal',
      },
    ],
  },
  {
    id: 'wo-0043',
    workOrderNumber: 'WO-2026-0043',
    reportedBy: 'Chef Sanjeewa',
    reportedById: 'user-exec-fb',
    departmentName: 'Kitchen & Culinary',
    location: 'Kitchen',
    category: 'Equipment',
    title: 'Walk-in Meat Freezer Evaporator Fan Heavy Vibration',
    description: 'Number 2 evaporator fan making loud clattering sound and vibrating violently.',
    guestAffected: false,
    priority: 'P2',
    suggestedPriority: 'P2',
    priorityRationale: 'Major food cold storage equipment at risk.',
    status: 'ACCEPTED',
    assignedTechnicianId: 'tech-pradeep',
    assignedTechnicianName: 'Pradeep Fernando',
    reportedAt: minutesAgo(35),
    acceptedAt: minutesAgo(30),
    acceptedBy: 'Sunil Shantha (Supervisor)',
    createdAt: minutesAgo(35),
    updatedAt: minutesAgo(30),
    history: [
      {
        id: 'hist-43-1',
        workOrderId: 'wo-0043',
        status: 'NEW',
        timestamp: minutesAgo(35),
        actorName: 'Chef Sanjeewa (Kitchen)',
        note: 'Reported issue',
      },
      {
        id: 'hist-43-2',
        workOrderId: 'wo-0043',
        status: 'ACCEPTED',
        timestamp: minutesAgo(30),
        actorName: 'Sunil Shantha (Supervisor)',
        note: 'Accepted and assigned to Pradeep Fernando',
      },
    ],
  },
  {
    id: 'wo-0042',
    workOrderNumber: 'WO-2026-0042',
    reportedBy: 'Anoma Gunasekara',
    reportedById: 'user-exec-fo',
    departmentName: 'Front Office',
    location: 'Lobby',
    category: 'Lighting',
    title: 'Main Lobby Center Chandelier Dimmer Flickering',
    description: 'Chandelier lights blinking intermittently when dimmed below 60%.',
    guestAffected: false,
    priority: 'P3',
    suggestedPriority: 'P3',
    priorityRationale: 'Public area visual lighting defect.',
    status: 'IN_PROGRESS',
    assignedTechnicianId: 'tech-kasun',
    assignedTechnicianName: 'Kasun Perera',
    reportedAt: hoursAgo(2),
    acceptedAt: hoursAgo(1.8),
    startedAt: hoursAgo(1.2),
    acceptedBy: 'Eng. Kasun Wijesinghe',
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(1.2),
    history: [
      {
        id: 'hist-42-1',
        workOrderId: 'wo-0042',
        status: 'NEW',
        timestamp: hoursAgo(2),
        actorName: 'Anoma Gunasekara (Front Office)',
        note: 'Reported issue',
      },
      {
        id: 'hist-42-2',
        workOrderId: 'wo-0042',
        status: 'ACCEPTED',
        timestamp: hoursAgo(1.8),
        actorName: 'Eng. Kasun Wijesinghe',
        note: 'Accepted request',
      },
      {
        id: 'hist-42-3',
        workOrderId: 'wo-0042',
        status: 'IN_PROGRESS',
        timestamp: hoursAgo(1.2),
        actorName: 'Kasun Perera (Technician)',
        note: 'Started work on dimmer control unit',
      },
    ],
  },
  {
    id: 'wo-0041',
    workOrderNumber: 'WO-2026-0041',
    reportedBy: 'Dilshan Rathnayake',
    reportedById: 'user-exec-hk',
    departmentName: 'Housekeeping',
    location: 'Guest Room',
    roomNumber: '404',
    category: 'Furniture',
    title: 'Balcony Glass Sliding Door Catch Lock Worn Out',
    description: 'Sliding door latch not locking firmly. Requires replacement catch bracket.',
    guestAffected: false,
    priority: 'P3',
    suggestedPriority: 'P3',
    status: 'WAITING',
    waitingReason: 'Waiting for spare sliding catch bracket from hardware store (ETA tomorrow 10:00 AM)',
    assignedTechnicianId: 'tech-suresh',
    assignedTechnicianName: 'Suresh Bandara',
    reportedAt: hoursAgo(4),
    acceptedAt: hoursAgo(3.8),
    startedAt: hoursAgo(3),
    waitingAt: hoursAgo(2),
    acceptedBy: 'Sunil Shantha (Supervisor)',
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(2),
    history: [
      { id: 'hist-41-1', workOrderId: 'wo-0041', status: 'NEW', timestamp: hoursAgo(4), actorName: 'Dilshan Rathnayake', note: 'Reported' },
      { id: 'hist-41-2', workOrderId: 'wo-0041', status: 'ACCEPTED', timestamp: hoursAgo(3.8), actorName: 'Sunil Shantha', note: 'Accepted' },
      { id: 'hist-41-3', workOrderId: 'wo-0041', status: 'IN_PROGRESS', timestamp: hoursAgo(3), actorName: 'Suresh Bandara', note: 'Inspected lock' },
      { id: 'hist-41-4', workOrderId: 'wo-0041', status: 'WAITING', timestamp: hoursAgo(2), actorName: 'Suresh Bandara', note: 'Put on hold: waiting for spare catch' },
    ],
  },
  {
    id: 'wo-0040',
    workOrderNumber: 'WO-2026-0040',
    reportedBy: 'Rohan Jayasuriya',
    reportedById: 'user-exec-fb',
    departmentName: 'F&B Service',
    location: 'Pool',
    category: 'Plumbing',
    title: 'Pool Deck Outdoor Shower Drain Blocked with Sand',
    description: 'Water ponding on the timber deck around outdoor shower 2.',
    guestAffected: false,
    priority: 'P2',
    suggestedPriority: 'P2',
    status: 'COMPLETED',
    assignedTechnicianId: 'tech-nimal',
    assignedTechnicianName: 'Nimal Silva',
    reportedAt: hoursAgo(5),
    acceptedAt: hoursAgo(4.5),
    startedAt: hoursAgo(4),
    completedAt: hoursAgo(3),
    acceptedBy: 'Sunil Shantha',
    workDone: 'Cleared drain trap with pressure hose. Removed sand buildup and re-fitted grating securely.',
    completionNote: 'Tested with full water flow. Draining freely without ponding.',
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(3),
    history: [
      { id: 'hist-40-1', workOrderId: 'wo-0040', status: 'NEW', timestamp: hoursAgo(5), actorName: 'Rohan Jayasuriya', note: 'Reported' },
      { id: 'hist-40-2', workOrderId: 'wo-0040', status: 'ACCEPTED', timestamp: hoursAgo(4.5), actorName: 'Sunil Shantha', note: 'Accepted' },
      { id: 'hist-40-3', workOrderId: 'wo-0040', status: 'IN_PROGRESS', timestamp: hoursAgo(4), actorName: 'Nimal Silva', note: 'Started drain clearing' },
      { id: 'hist-40-4', workOrderId: 'wo-0040', status: 'COMPLETED', timestamp: hoursAgo(3), actorName: 'Nimal Silva', note: 'Marked Completed' },
    ],
  },
  {
    id: 'wo-0039',
    workOrderNumber: 'WO-2026-0039',
    reportedBy: 'Ruwan Senanayake',
    reportedById: 'user-admin',
    departmentName: 'Administration & HR',
    location: 'Staff Area',
    category: 'Plumbing',
    title: 'Staff Canteen Water Dispenser Push Button Leaking',
    description: 'Hot water push button spring stuck open.',
    guestAffected: false,
    priority: 'P3',
    suggestedPriority: 'P3',
    status: 'CLOSED',
    assignedTechnicianId: 'tech-nimal',
    assignedTechnicianName: 'Nimal Silva',
    reportedAt: daysAgo(1),
    acceptedAt: daysAgo(1),
    startedAt: daysAgo(1),
    completedAt: daysAgo(1),
    closedAt: daysAgo(1),
    acceptedBy: 'Sunil Shantha',
    closedBy: 'Eng. Kasun Wijesinghe',
    workDone: 'Replaced spring loaded silicone push valve on dispenser.',
    completionNote: 'Tested and verified no leaks.',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    history: [
      { id: 'hist-39-1', workOrderId: 'wo-0039', status: 'NEW', timestamp: daysAgo(1), actorName: 'Ruwan Senanayake', note: 'Reported' },
      { id: 'hist-39-2', workOrderId: 'wo-0039', status: 'ACCEPTED', timestamp: daysAgo(1), actorName: 'Sunil Shantha', note: 'Accepted' },
      { id: 'hist-39-3', workOrderId: 'wo-0039', status: 'IN_PROGRESS', timestamp: daysAgo(1), actorName: 'Nimal Silva', note: 'Repaired valve' },
      { id: 'hist-39-4', workOrderId: 'wo-0039', status: 'COMPLETED', timestamp: daysAgo(1), actorName: 'Nimal Silva', note: 'Completed' },
      { id: 'hist-39-5', workOrderId: 'wo-0039', status: 'CLOSED', timestamp: daysAgo(1), actorName: 'Eng. Kasun Wijesinghe', note: 'Verified and Closed' },
    ],
  },
];
